#!/usr/bin/env python

# Client for submitting feature files to the Acousticbrainz project

# Copyright 2014 Music Technology Group - Universitat Pompeu Fabra
# acousticbrainz-client is available under the terms of the GNU
# General Public License, version 3 or higher. See COPYING for more details.

import argparse
from abz import acousticbrainz

if __name__ == "__main__":
    p = argparse.ArgumentParser(description="Acousticbrainz client")
    p.add_argument("p", help="Path to upload", nargs='*')
    p.add_argument("--processes", help="Number of processes to spawn",
                   default=None, type=int, action="store")

    args = p.parse_args()
    if args.p:
        acousticbrainz.main(args)
    else:
        p.print_usage()
