#!/usr/bin/env python

import argparse
from abz import acousticbrainz

if __name__ == "__main__":
    p = argparse.ArgumentParser(description="Acousticbrainz client")
    p.add_argument("p", help="Path to upload", nargs='*')
    p.add_argument("--processes", help="Number of processes to spawn",
                   default=None, type=int, action="store")

    args = p.parse_args()
    if args.p:
        acousticbrainz.main(args)
    else:
        p.print_usage()
